'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Partial Public Class Main
   Protected WithEvents form1 As System.Web.UI.HtmlControls.HtmlForm
   Protected WithEvents lblError As System.Web.UI.WebControls.Label
   Protected WithEvents ddlConversionType As System.Web.UI.WebControls.DropDownList
   Protected WithEvents btnParseFile As System.Web.UI.WebControls.Button
   Protected WithEvents txtControlFileDetails As System.Web.UI.WebControls.TextBox
   Protected WithEvents lnkViewControlFile As System.Web.UI.WebControls.HyperLink
   Protected WithEvents txtRawData As System.Web.UI.WebControls.TextBox
   Protected WithEvents gvResults As System.Web.UI.WebControls.GridView
End Class
